---
title: "Class 05: Data Visualization with GGPLOT"
author: "Karen Guerrero"
format: pdf
toc: true
---

# Our first plot

R has base graphics

```{r}
cars
```

```{r}
plot(cars)
```
```{r}
head(cars)
```


```{r}
library(ggplot2)
```

How would I plot this with 'ggplot2'?

```{r}
ggplot(cars)
```

Every ggplot needs at least 3 layers:

-**Data** (i.e. the data.frame we have),
-**Aes** (the asethetic mapping of our data to what we want to plot)
-**Geoms** (How we want to plot this stuff!)

```{r}
ggplot(cars) + aes(x=speed, y=dist)
```

```{r}
ggplot(cars) + aes(x=speed, y=dist) + geom_point()
```

```{r}
ggplot(cars) + aes(x=speed, y=dist) + geom_point() + geom_line()
```


```{r}
ggplot(cars) + aes(x=speed, y=dist) + geom_point() + geom_smooth()
```

```{r}
ggplot(cars) + aes(x=speed, y=dist) + geom_point() + geom_smooth(method="lm", se=FALSE) 
```
```{r}
ggplot(cars) + aes(x=speed, y=dist) + geom_point() + geom_smooth(method="lm", se=FALSE) + labs(title="Speed and Stopping Distances of Cars", x="Speed (MPH)", y="Stopping Distance (ft)", subtitle = "Your informative subtitle text here", caption = "Dataset: 'cars'") + theme_bw()
```

```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
```

```{r}
nrow(genes)
```

There are `r nrow(genes)` genes in this data set.

```{r}
colnames(genes)
ncol(genes)
```
```{r}
table(genes$State)
```

```{r}
round( table(genes$State)/nrow(genes) * 100, 2 )
```
```{r}
ggplot(genes) + aes(x=Condition1, y=Condition2) + geom_point()
```
```{r}
p <- ggplot(genes) + aes(x=Condition1, y=Condition2, col=State) + geom_point()
p
```
```{r}
p + scale_colour_manual( values=c("blue","gray","red") )
```

```{r}
p + scale_colour_manual( values=c("blue","gray","red") ) + labs(title="Gene Expression Changes Upon Drug Treatment", x="Control (No Drug)", y="Drug Treatment")
```
```{r}
#install.packages("gapminder")
library(gapminder)
```

```{r}
#install.packages("dplyr")
```

```{r}
library(dplyr)

gapminder_2007 <- gapminder %>% filter(year==2007)
```

```{r}
ggplot(gapminder_2007) + aes(x=gdpPercap, y=lifeExp) + geom_point()
```

```{r}
ggplot(gapminder_2007) + aes(x=gdpPercap, y=lifeExp) + geom_point(alpha=0.5)
```

```{r}
ggplot(gapminder_2007) + aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) + geom_point(alpha=0.5)
```

```{r}
ggplot(gapminder_2007) + aes(x=gdpPercap, y=lifeExp, color=pop) + geom_point(alpha=0.8)
```

```{r}
ggplot(gapminder_2007) + aes(x=gdpPercap, y=lifeExp, size=pop) + geom_point(alpha=0.5)
```


```{r}
ggplot(gapminder_2007) + geom_point(aes(x = gdpPercap, y = lifeExp, size = pop), alpha=0.5) + scale_size_area(max_size = 10)
```

```{r}
gapminder_1957 <- gapminder %>% filter(year==1957)
ggplot(gapminder_1957) + aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) + geom_point(alpha=0.7) + scale_size_area(max_size = 15)
```

```{r}
gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)
ggplot(gapminder_1957) + aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) + geom_point(alpha=0.7) + scale_size_area(max_size = 15) + facet_wrap(~year)
```

```{r}
gapminder_top5 <- gapminder %>% filter(year==2007) %>% arrange(desc(pop)) %>% top_n(5, pop)
gapminder_top5
```

```{r}
ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop))
```

```{r}
ggplot(gapminder_top5) + geom_col(aes(x = country, y = lifeExp))
```

```{r}
ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop, fill=continent))
```

```{r}
ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop, fill=lifeExp))
```

```{r}
ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop, fill=gdpPercap))
```

```{r}
ggplot(gapminder_top5) + geom_col(aes(x = reorder(country, -pop), y = pop, fill=gdpPercap))
```

```{r}
ggplot(gapminder_top5) + aes(x = reorder(country, -pop), y = pop, fill=country) + geom_col( col="gray30") +   guides(fill="none")
```

```{r}
head(USArrests)
```

```{r}
USArrests$State <- rownames(USArrests)
ggplot(USArrests) + aes(x=reorder(State,Murder), y=Murder) + geom_col() + coord_flip()
```

```{r}
ggplot(USArrests) + aes(x=reorder(State,Murder), y=Murder) + geom_point() + geom_segment(aes(x=State, xend=State, y=0, yend=Murder), color="blue") + coord_flip()

```

```{r}
library(gapminder)
library(gganimate)

```

```{r}
ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  # Facet by continent
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  shadow_wake(wake_length = 0.1, alpha = FALSE)
```

```{r}
library(patchwork)
```

```{r}
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))
p4 <- ggplot(mtcars) + geom_bar(aes(carb))
```

```{r}
(p1 | p2 | p3) / p4
```
